### ISSUE TITLE
`soroban contract new` command

### ISSUE THREAD

**Issue by tyvdh** [stellar/soroban-tools#1012] opened 2023-10-06 13:56 UTC
I find myself going through the process here https://soroban.stellar.org/docs/getting-started/hello-world more times than I care to admit. It would be _very_ nice to have a command which could do this for me.

I propose `soroban contract new`

I would also propose we allow a `--template` flag that let's you pick a https://github.com/stellar/soroban-examples directory to clone which maybe further down the line we could create a specific repo with even more or custom user provided templates.

Either way, allowing devs to get a project scaffold stood up quickly would be a huge win imo

**Comment by leighmcculloch** [comment] 2023-10-06 15:54
+1 duplicate of https://github.com/stellar/soroban-tools/issues/656.

Could you post your idea example of how it'd work with a template? Although I think we should ship this ASAP with a builtin template and add customizability later. We'd get so much value from at least a default.

**Closed by leighmcculloch** 2023-10-06 15:54 UTC
