### ISSUE TITLE
Unable to use Option<> in a struct

### ISSUE THREAD

**Issue by Julian-dev28** [stellar/soroban-tools#1080] opened 2023-11-13 20:10 UTC
### What version are you using?

soroban-sdk = { version = "20.0.0-rc2" }

### What did you do?

I'm working on creating a "Battle" struct that designates a winner (Address) once the battle ends. Initially, when a battle is created, there won't be a winner. To handle this, I used the Option<> type within the struct, setting the winner to `None` at the creation of the battle.

    #[contracttype]
    #[derive(Clone, Debug, Eq, PartialEq)]
    pub struct Battle {
        pub battle_status: u64,
        pub name: Symbol,
        pub players: Vec<Address>,
        pub moves: Vec<u64>,
        pub winner: Option<Address>,
    }
    
    
    pub fn create_battle(env: Env, name: Symbol, user: Address, _winner: Option<Address>) {
        user.require_auth();
        env.storage().instance().set(
            &DataKey::Battle(name.clone()),
            &Battle {
                battle_status: 0,
                name: name.clone(),
                players: vec![&env, user.clone()],
                moves: Vec::new(&env),
                winner: None,
            },
        );
      ...

### What did you expect to see?

No errors

### What did you see instead?

An error stating that the trait is not satisfied.

    error[E0277]: the trait bound `core::option::Option<soroban_sdk::Address>: SorobanArbitrary` is not satisfied
      --> src/lib.rs:23:1
       |
    23 | #[contracttype]
       | ^^^^^^^^^^^^^^^ the trait `SorobanArbitrary` is not implemented for `core::option::Option<soroban_sdk::Address>`
       |
       = help: the following other types implement trait `SorobanArbitrary`:
                 bool
                 i32
                 i64
                 i128
                 u32
                 u64
                 u128
                 DataKey
               and 22 others
       = note: this error originates in the attribute macro `contracttype` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by leighmcculloch** [comment] 2023-11-13 20:12
Closing because this is a duplicate of:
- https://github.com/stellar/rs-soroban-env/issues/444
- https://github.com/stellar/rs-soroban-sdk/issues/877

Please subscribe to those issues to track.

The fix for this bug is in progress and should be in the next release. 🤞🏻

**Comment by Julian-dev28** [comment] 2023-11-13 20:13
Thanks @leighmcculloch 

Will track those instead!

**Closed by leighmcculloch** 2023-11-13 20:12 UTC
Labels: bug
