### ISSUE TITLE
Soroban RPC - shutdown not clean

### ISSUE THREAD

**Issue by jcx120** [stellar/soroban-tools#869] opened 2023-08-17 23:05 UTC
### What version are you using?
Preview 10

### What did you do?
Tried to shutdown the RPC, it did not do so cleanly:

This is using https://hub.docker.com/r/stellar/soroban-rpc ... looks like docker stop does not shut things down cleanly. using a persistent db

reported from [discord user](https://discord.com/channels/897514728459468821/966788672164855829/1139611596734349363)

### What did you expect to see?
clean shutdown

### What did you see instead?
```
time="2023-08-11T17:29:04.281Z" level=info msg="Tx: applying ledger 343258 (classic phase: 1 component(s): [{discounted txs:1, ops:1, base_fee:100}], soroban phase: 1 component(s): [{discounted txs:1, ops:1, base_fee:100}])" pid=1 subservice=stellar-core
time="2023-08-11T17:29:04.283Z" level=error msg="Tx: Exception while applying operations (fullHash = 976358c7a45be23d687ff62a05f8cc4acc6b942a6e50b2d50922eaaca762538a" pid=1 subservice=stellar-core
time="2023-08-11T17:29:04.283Z" level=info msg=", contentsHash = 029871781e6e2510617b7949f4b109e27cd60554456924be6a3dd90deaa619f8" pid=1 subservice=stellar-core
time="2023-08-11T17:29:04.283Z" level=info msg="): Key already exists" pid=1 subservice=stellar-core
time="2023-08-11T17:29:04.293Z" level=info msg="default: Application destructing" pid=1 subservice=stellar-core
time="2023-08-11T17:29:04.295Z" level=info msg="default: Application destroyed" pid=1 subservice=stellar-core
time="2023-08-11T17:29:04.415Z" level=error msg="default: Got an exception: Local node's ledger corrupted during close" pid=1 subservice=stellar-core
time="2023-08-11T17:29:04.415Z" level=error msg="default: Please report this bug along with this log file if this was not expected" pid=1 subservice=stellar-core
time="2023-08-11T17:29:04.423Z" level=error msg="could not run ingestion. Retrying" error="error starting prepare range: opening subprocess: error running stellar-core: error runing stellar-core catchup: exit status 1" pid=1
time="2023-08-11T17:29:05.424Z" level=info msg="Applying txmeta for ledger 343296" pid=1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xee8624]
```

**Comment by tsachiherman** [comment] 2023-10-27 16:20
I was unable to reproduce with latest preview 11 build.
Even with patches to core to generate a similar failure, the issue is not observable on the go side.
I'll be closing this issue for now. If it ever being reported again, please re-open.

**Closed by tsachiherman** 2023-10-27 16:20 UTC
Labels: bug
